# Generated by Django 5.2.5 on 2025-08-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_hero_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='alias',
            field=models.CharField(max_length=40),
        ),
    ]
